# Generated by Django 3.1.1 on 2020-11-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=45, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(blank=True, max_length=45, null=True)),
                ('admin_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_company_master',
                'managed': False,
            },
        ),
    ]
